language: node_js
os: linux

node_js:
- '10'

services:
  - docker

cache:
  directories:
     - ./node_modules
     - ./client/node_modules
     - ./client-dist
     - ./server-dist

script:
  - ./build-all.sh

