language: node_js
os: linux

node_js:
- 'lts/*'

services:
  - docker

cache:
  directories:
     - ./node_modules
     - ./client/node_modules
     - ./client-dist
     - ./server-dist

jobs:
  include:
    - stage: build
      script: "./build-all.sh"
    - stage: deploy
      script: "./build-all-deploy.sh"

stages:
  - name: build
    if: (NOT ((branch = master) AND (NOT (type IN (pull_request)))))
  - name: deploy
    if: (branch = master) AND (NOT (type IN (pull_request)))
