language: node_js
os: linux

node_js:
- '12'

services:
  - docker

cache:
  directories:
     - ./node_modules
     - ./client/node_modules
     - ./client-dist
     - ./server-dist

jobs:
  include:
    - stage: build
      script: "./build-all.sh"
      - stage: deploy
      script: "./docker-deploy.sh"

stages:
  - name: build
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: (branch = master) AND (NOT (type IN (push, pull_request)))

