language: node_js
os: linux
sudo: false
node_js:
- '10'

cache:
  directories:
     - ./node_modules
     - ./client/node_modules
     - ./client-dist
     - ./server-dist

script:
  - ./build-all.sh

