language: node_js
os: linux

node_js:
- '12'

services:
  - docker

cache:
  directories:
     - ./node_modules
     - ./client/node_modules
     - ./client-dist
     - ./server-dist

stages:
  - name: build
    script:
      - ./build-all.sh
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
    script:
      - ./docker-deploy.sh
