language: node_js
os: linux

node_js:
- '12'

services:
  - docker

cache:
  directories:
     - ./node_modules
     - ./client/node_modules
     - ./client-dist
     - ./server-dist

script:
  - ./build-all.sh
  - ./docker-deploy.sh
